name: Development workflow

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node-versions: ['20.x', '21.x', '22.x']
        os: [ubuntu-22.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install

      - name: Check for lint errors
        if: matrix.os != 'windows-latest'
        run: |
          pnpm check:ci src cypress

      - name: Run tests
        run: |
          pnpm test

  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup packages
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: pnpm build
          start: pnpm dev
          browser: chrome
          record: true
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 60
          parallel: true
          tag: ${{ github.sha }}
          spec: 'cypress/e2e/**/*.spec.js'
          install-command: pnpm install
